language: node_js
node_js:
   - "0.11"
   - "0.10"
cache:
  directories:
    - node_modules
install:
   - npm install
   - npm install -g bower jshint gulp tsd bower-installer
   - tsd update --overwrite
   - bower install
